### ISSUE TITLE
Add support for other events

### ISSUE THREAD

**Issue by dkwiebe** [LiveHelperChat/lhchatevents#1]
We'd like to build on this and I'm wondering if you'd be interested in moving it into the core product.  I'd like to be able to send REST POSTS on a large variety of events such as a chat starting, ending, chats where the response is delayed, etc.

What I was thinking is getting all events posted to our REST API.

**Comment by remdex** [comment]
To late, but at-least something :)
https://doc.livehelperchat.com/docs/hooks
